name: nihonix
description: "A Japanese learning app built with Flutter."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization (multi-language & date/number formats)
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod:

  # Navigation & routing
  go_router:

  # HTTP & API calls
  dio:

  # Local database (offline storage)
  hive:
  hive_flutter:

  # Utilities
  equatable:         # Object equality
  logger:            # Simple logging
  pretty_dio_logger: # HTTP request/response logs
  connectivity_plus: # Network status check
  intl:              # Internationalization utils
  package_info_plus: # App info (name, version)
  url_launcher:      # Open URLs, calls, emails

  # iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code style & lints
  flutter_lints: ^6.0.0

  # Code generation tools
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
